packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@types/bun": ^1.3.4
  hono: ^4.8.2
  "@trpc/server": ^11.7.2
  better-auth: ^1.4.7
  ai: ^5.0.49
  "@ai-sdk/google": ^2.0.13
  "@tanstack/react-query": ^5.90.12
  "@trpc/tanstack-react-query": ^11.7.2
  "@trpc/client": ^11.7.2
  "@ai-sdk/react": ^2.0.39
  "@better-auth/expo": ^1.4.7
  drizzle-orm: ^0.45.1
  "@types/pg": ^8.15.6
