/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntitiesRouteRouteImport } from './routes/entities/route'
import { Route as DealsRouteRouteImport } from './routes/deals/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntitiesIndexRouteImport } from './routes/entities/index'
import { Route as DealsIndexRouteImport } from './routes/deals/index'
import { Route as EntitiesEntitySlugRouteRouteImport } from './routes/entities/$entitySlug/route'
import { Route as EntitiesEntitySlugIndexRouteImport } from './routes/entities/$entitySlug/index'
import { Route as EntitiesEntitySlugRecordIdRouteImport } from './routes/entities/$entitySlug/$recordId'
import { Route as DealsDealIdStageIdRouteImport } from './routes/deals/$dealId.$stageId'
import { Route as EntitiesEntitySlugSettingsRouteRouteImport } from './routes/entities/$entitySlug/settings/route'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRouteRoute = EntitiesRouteRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRouteRoute = DealsRouteRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntitiesRouteRoute,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DealsRouteRoute,
} as any)
const EntitiesEntitySlugRouteRoute = EntitiesEntitySlugRouteRouteImport.update({
  id: '/$entitySlug',
  path: '/$entitySlug',
  getParentRoute: () => EntitiesRouteRoute,
} as any)
const EntitiesEntitySlugIndexRoute = EntitiesEntitySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntitiesEntitySlugRouteRoute,
} as any)
const EntitiesEntitySlugRecordIdRoute =
  EntitiesEntitySlugRecordIdRouteImport.update({
    id: '/$recordId',
    path: '/$recordId',
    getParentRoute: () => EntitiesEntitySlugRouteRoute,
  } as any)
const DealsDealIdStageIdRoute = DealsDealIdStageIdRouteImport.update({
  id: '/$dealId/$stageId',
  path: '/$dealId/$stageId',
  getParentRoute: () => DealsRouteRoute,
} as any)
const EntitiesEntitySlugSettingsRouteRoute =
  EntitiesEntitySlugSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => EntitiesEntitySlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deals': typeof DealsRouteRouteWithChildren
  '/entities': typeof EntitiesRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/entities/$entitySlug': typeof EntitiesEntitySlugRouteRouteWithChildren
  '/deals/': typeof DealsIndexRoute
  '/entities/': typeof EntitiesIndexRoute
  '/entities/$entitySlug/settings': typeof EntitiesEntitySlugSettingsRouteRoute
  '/deals/$dealId/$stageId': typeof DealsDealIdStageIdRoute
  '/entities/$entitySlug/$recordId': typeof EntitiesEntitySlugRecordIdRoute
  '/entities/$entitySlug/': typeof EntitiesEntitySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/deals': typeof DealsIndexRoute
  '/entities': typeof EntitiesIndexRoute
  '/entities/$entitySlug/settings': typeof EntitiesEntitySlugSettingsRouteRoute
  '/deals/$dealId/$stageId': typeof DealsDealIdStageIdRoute
  '/entities/$entitySlug/$recordId': typeof EntitiesEntitySlugRecordIdRoute
  '/entities/$entitySlug': typeof EntitiesEntitySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deals': typeof DealsRouteRouteWithChildren
  '/entities': typeof EntitiesRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/entities/$entitySlug': typeof EntitiesEntitySlugRouteRouteWithChildren
  '/deals/': typeof DealsIndexRoute
  '/entities/': typeof EntitiesIndexRoute
  '/entities/$entitySlug/settings': typeof EntitiesEntitySlugSettingsRouteRoute
  '/deals/$dealId/$stageId': typeof DealsDealIdStageIdRoute
  '/entities/$entitySlug/$recordId': typeof EntitiesEntitySlugRecordIdRoute
  '/entities/$entitySlug/': typeof EntitiesEntitySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deals'
    | '/entities'
    | '/login'
    | '/onboarding'
    | '/entities/$entitySlug'
    | '/deals/'
    | '/entities/'
    | '/entities/$entitySlug/settings'
    | '/deals/$dealId/$stageId'
    | '/entities/$entitySlug/$recordId'
    | '/entities/$entitySlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/deals'
    | '/entities'
    | '/entities/$entitySlug/settings'
    | '/deals/$dealId/$stageId'
    | '/entities/$entitySlug/$recordId'
    | '/entities/$entitySlug'
  id:
    | '__root__'
    | '/'
    | '/deals'
    | '/entities'
    | '/login'
    | '/onboarding'
    | '/entities/$entitySlug'
    | '/deals/'
    | '/entities/'
    | '/entities/$entitySlug/settings'
    | '/deals/$dealId/$stageId'
    | '/entities/$entitySlug/$recordId'
    | '/entities/$entitySlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DealsRouteRoute: typeof DealsRouteRouteWithChildren
  EntitiesRouteRoute: typeof EntitiesRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/': {
      id: '/entities/'
      path: '/'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof EntitiesRouteRoute
    }
    '/deals/': {
      id: '/deals/'
      path: '/'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof DealsRouteRoute
    }
    '/entities/$entitySlug': {
      id: '/entities/$entitySlug'
      path: '/$entitySlug'
      fullPath: '/entities/$entitySlug'
      preLoaderRoute: typeof EntitiesEntitySlugRouteRouteImport
      parentRoute: typeof EntitiesRouteRoute
    }
    '/entities/$entitySlug/': {
      id: '/entities/$entitySlug/'
      path: '/'
      fullPath: '/entities/$entitySlug/'
      preLoaderRoute: typeof EntitiesEntitySlugIndexRouteImport
      parentRoute: typeof EntitiesEntitySlugRouteRoute
    }
    '/entities/$entitySlug/$recordId': {
      id: '/entities/$entitySlug/$recordId'
      path: '/$recordId'
      fullPath: '/entities/$entitySlug/$recordId'
      preLoaderRoute: typeof EntitiesEntitySlugRecordIdRouteImport
      parentRoute: typeof EntitiesEntitySlugRouteRoute
    }
    '/deals/$dealId/$stageId': {
      id: '/deals/$dealId/$stageId'
      path: '/$dealId/$stageId'
      fullPath: '/deals/$dealId/$stageId'
      preLoaderRoute: typeof DealsDealIdStageIdRouteImport
      parentRoute: typeof DealsRouteRoute
    }
    '/entities/$entitySlug/settings': {
      id: '/entities/$entitySlug/settings'
      path: '/settings'
      fullPath: '/entities/$entitySlug/settings'
      preLoaderRoute: typeof EntitiesEntitySlugSettingsRouteRouteImport
      parentRoute: typeof EntitiesEntitySlugRouteRoute
    }
  }
}

interface DealsRouteRouteChildren {
  DealsIndexRoute: typeof DealsIndexRoute
  DealsDealIdStageIdRoute: typeof DealsDealIdStageIdRoute
}

const DealsRouteRouteChildren: DealsRouteRouteChildren = {
  DealsIndexRoute: DealsIndexRoute,
  DealsDealIdStageIdRoute: DealsDealIdStageIdRoute,
}

const DealsRouteRouteWithChildren = DealsRouteRoute._addFileChildren(
  DealsRouteRouteChildren,
)

interface EntitiesEntitySlugRouteRouteChildren {
  EntitiesEntitySlugSettingsRouteRoute: typeof EntitiesEntitySlugSettingsRouteRoute
  EntitiesEntitySlugRecordIdRoute: typeof EntitiesEntitySlugRecordIdRoute
  EntitiesEntitySlugIndexRoute: typeof EntitiesEntitySlugIndexRoute
}

const EntitiesEntitySlugRouteRouteChildren: EntitiesEntitySlugRouteRouteChildren =
  {
    EntitiesEntitySlugSettingsRouteRoute: EntitiesEntitySlugSettingsRouteRoute,
    EntitiesEntitySlugRecordIdRoute: EntitiesEntitySlugRecordIdRoute,
    EntitiesEntitySlugIndexRoute: EntitiesEntitySlugIndexRoute,
  }

const EntitiesEntitySlugRouteRouteWithChildren =
  EntitiesEntitySlugRouteRoute._addFileChildren(
    EntitiesEntitySlugRouteRouteChildren,
  )

interface EntitiesRouteRouteChildren {
  EntitiesEntitySlugRouteRoute: typeof EntitiesEntitySlugRouteRouteWithChildren
  EntitiesIndexRoute: typeof EntitiesIndexRoute
}

const EntitiesRouteRouteChildren: EntitiesRouteRouteChildren = {
  EntitiesEntitySlugRouteRoute: EntitiesEntitySlugRouteRouteWithChildren,
  EntitiesIndexRoute: EntitiesIndexRoute,
}

const EntitiesRouteRouteWithChildren = EntitiesRouteRoute._addFileChildren(
  EntitiesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DealsRouteRoute: DealsRouteRouteWithChildren,
  EntitiesRouteRoute: EntitiesRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
