/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntitiesEntitySlugRouteImport } from './routes/entities.$entitySlug'
import { Route as EntitiesEntitySlugSettingsRouteImport } from './routes/entities.$entitySlug.settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntitySlugRoute = EntitiesEntitySlugRouteImport.update({
  id: '/$entitySlug',
  path: '/$entitySlug',
  getParentRoute: () => EntitiesRoute,
} as any)
const EntitiesEntitySlugSettingsRoute =
  EntitiesEntitySlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => EntitiesEntitySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/login': typeof LoginRoute
  '/entities/$entitySlug': typeof EntitiesEntitySlugRouteWithChildren
  '/entities/$entitySlug/settings': typeof EntitiesEntitySlugSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/login': typeof LoginRoute
  '/entities/$entitySlug': typeof EntitiesEntitySlugRouteWithChildren
  '/entities/$entitySlug/settings': typeof EntitiesEntitySlugSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/login': typeof LoginRoute
  '/entities/$entitySlug': typeof EntitiesEntitySlugRouteWithChildren
  '/entities/$entitySlug/settings': typeof EntitiesEntitySlugSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entities'
    | '/login'
    | '/entities/$entitySlug'
    | '/entities/$entitySlug/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entities'
    | '/login'
    | '/entities/$entitySlug'
    | '/entities/$entitySlug/settings'
  id:
    | '__root__'
    | '/'
    | '/entities'
    | '/login'
    | '/entities/$entitySlug'
    | '/entities/$entitySlug/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntitiesRoute: typeof EntitiesRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entitySlug': {
      id: '/entities/$entitySlug'
      path: '/$entitySlug'
      fullPath: '/entities/$entitySlug'
      preLoaderRoute: typeof EntitiesEntitySlugRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/entities/$entitySlug/settings': {
      id: '/entities/$entitySlug/settings'
      path: '/settings'
      fullPath: '/entities/$entitySlug/settings'
      preLoaderRoute: typeof EntitiesEntitySlugSettingsRouteImport
      parentRoute: typeof EntitiesEntitySlugRoute
    }
  }
}

interface EntitiesEntitySlugRouteChildren {
  EntitiesEntitySlugSettingsRoute: typeof EntitiesEntitySlugSettingsRoute
}

const EntitiesEntitySlugRouteChildren: EntitiesEntitySlugRouteChildren = {
  EntitiesEntitySlugSettingsRoute: EntitiesEntitySlugSettingsRoute,
}

const EntitiesEntitySlugRouteWithChildren =
  EntitiesEntitySlugRoute._addFileChildren(EntitiesEntitySlugRouteChildren)

interface EntitiesRouteChildren {
  EntitiesEntitySlugRoute: typeof EntitiesEntitySlugRouteWithChildren
}

const EntitiesRouteChildren: EntitiesRouteChildren = {
  EntitiesEntitySlugRoute: EntitiesEntitySlugRouteWithChildren,
}

const EntitiesRouteWithChildren = EntitiesRoute._addFileChildren(
  EntitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntitiesRoute: EntitiesRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
